- name: Configure vsftpd
  hosts: myserver1 
  become: true
  become_user: root
  tasks:
  - name: Check Ansible distribution
    command: ansible --version
    register: ansible_distribution
  - name: Print Ansible distribution
    debug:
      var: ansible_distribution.stdout
  - name: Install vsftpd
    yum:
      name: vsftpd
      state: present
  - name: Start vsftpd service if Ansible distribution is Ubuntu
    when: ansible_distribution.stdout == 'Ubuntu'
    service:
      name: vsftpd
      state: started
      enabled: yes

  - name: End the play if Ansible distribution is not Ubuntu
    when: ansible_distribution.stdout != 'Ubuntu'
    meta: end_play
