- name: Create and Remove Files
  hosts: myserver1
  become: true
  become_user: user
  gather_facts: false
  tasks:
  - name: Create file
    file:
      path: <your path>/Kubernetes.txt
      state: touch
    register: create_result

  - name: Display create result
    debug:
      var: create_result

  - name: Remove file
    file:
      path: <your path>/name.json
      state: absent
    register: remove_result

  - name: Display remove result
    debug:
      var: remove_result
