---
- name: Check if repo exists
  hosts: myserver1 
  become: true
  become_user: root 
  tasks:
  - name: Get the repo details
    stat:
      path: /etc/yum.repos.d/kube.repo
    register: repo_details

  - name: Check if repo exists
    debug:
      var: repo_details.stat.exists

  - name: Do something if repo does not exist
    command: echo "Repo does not exist"
    when: not repo_details.stat.exists