- name: Checking the Nodejs application request 
  hosts: localhost 
  become: true 
  become_user: hr214 
  tasks:
    - name: Check if Nodejs application is up 
      uri:
        URL: <website Ip>
        method: GET
        return_content: yes
      register: Nodejs_status

    - name: Print the status code of Nodejs 
      debug:
        msg: "{{ Nodejs_status.content }}"
